name: flutter_coffesshop_ui
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  
  gap: ^3.0.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  readmore: ^3.0.0
  google_maps_flutter: ^2.0.6
  flutter_bloc: ^8.1.6


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
